name: Generate Javadoc

# Triggers the workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Generate Javadoc
        run: |
          mkdir -p CalculatorSDK/docs
          javadoc -sourcepath CalculatorSDK/src/*.java -d  CalculatorSDK/docs
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Javadoc
        run: |
          git add CalculatorSDK/docs
          git commit -m "Update Javadoc"
          git push origin main
